# docker build -t tomdush/circleci-go-aws:1.9 . && docker push tomdush/circleci-go-aws:1.9
FROM circleci/golang:1.9
MAINTAINER Thomas Duchatelle <duchatelle.thomas@gmail.com>

RUN sudo apt-get update && sudo apt-get install -y awscli